spring.application.name=soccer-predictor-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/soccerdb
spring.datasource.username=postgres
spring.datasource.password=20042511k
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
sports.api.key=2a67a87911b44862bc64de28ae90747f